/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultContent: typeof import('./components/layouts/defaultLayout/components/defaultContent.vue')['default']
    DefaultFooter: typeof import('./components/layouts/defaultLayout/components/defaultFooter.vue')['default']
    DefaultLayout: typeof import('./components/layouts/defaultLayout/index.vue')['default']
    DefaultNavbar: typeof import('./components/layouts/defaultLayout/components/defaultNavbar.vue')['default']
    DefaultSidebar: typeof import('./components/layouts/defaultLayout/components/defaultSidebar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    Home: typeof import('./components/home/home.vue')['default']
    Login: typeof import('./components/auth/components/login/index.vue')['default']
    LoginForm: typeof import('./components/auth/components/login/loginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
