/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultContent: typeof import('./components/layouts/defaultLayout/components/defaultContent.vue')['default']
    DefaultFooter: typeof import('./components/layouts/defaultLayout/components/defaultFooter.vue')['default']
    DefaultLayout: typeof import('./components/layouts/defaultLayout/index.vue')['default']
    DefaultNavbar: typeof import('./components/layouts/defaultLayout/components/defaultNavbar.vue')['default']
    DefaultSidebar: typeof import('./components/layouts/defaultLayout/components/defaultSidebar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    Home: typeof import('./components/home/home.vue')['default']
    LoginForm: typeof import('./components/auth/components/loginForm/loginForm.vue')['default']
    PersonForm: typeof import('./components/auth/components/registerForm/forms/personForm.vue')['default']
    RegisterForm: typeof import('./components/auth/components/registerForm/registerForm.vue')['default']
    RegisterPerson: typeof import('./components/auth/components/registerForm/registerPerson.vue')['default']
    RegisterUser: typeof import('./components/auth/components/registerForm/registerUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./components/auth/components/registerForm/forms/userForm.vue')['default']
  }
}
